version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
  - package-ecosystem: npm
    directories:
      - '/'
      - '/packages/server/functions'
      - '/packages/cli'
      - '/packages/web'
      - '/packages/storage'
      - '/packages/translations'
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 25
    groups:
      rollup:
        patterns:
          - '*rollup*'
      jest:
        patterns:
          - '*jest*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - '@*eslin*/*'
      material:
        patterns:
          - '@material/*'
      firebase:
        patterns:
          - '*firebase*'
      typescript:
        patterns:
          - 'typescript'
      node:
        patterns:
          - '@types/node'
