/* eslint-disable no-unused-vars */
// ui
const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
const SET_VIEWPORT_SIZE = 'SET_VIEWPORT_SIZE';
const SET_HERO_SETTINGS = 'SET_HERO_SETTINGS';
// router
const SET_ROUTE = 'SET_ROUTE';
const SET_SUB_ROUTE = 'SET_SUB_ROUTE';
// dialogs
const OPEN_DIALOG = 'OPEN_DIALOG';
const CLOSE_DIALOG = 'CLOSE_DIALOG';
const SET_DIALOG_DATA = 'SET_DIALOG_DATA';
const DIALOGS = {
  SPEAKER: 'speaker',
  PREVIOUS_SPEAKER: 'previousSpeaker',
  SESSION: 'session',
  SUBSCRIBE: 'subscribe',
  SIGNIN: 'signin',
};
// toast
const SHOW_TOAST = 'SHOW_TOAST';
const HIDE_TOAST = 'HIDE_TOAST';

// tickets
const FETCH_TICKETS = 'app/Tickets/FETCH_TICKETS';
const FETCH_TICKETS_FAILURE = 'app/Tickets/FETCH_TICKETS_FAILURE';
const FETCH_TICKETS_SUCCESS = 'app/Tickets/FETCH_TICKETS_SUCCESS';

// partners
const FETCH_PARTNERS = 'FETCH_PARTNERS';

// featured videos
const FETCH_VIDEOS = 'app/Videos/FETCH_VIDEOS';
const FETCH_VIDEOS_FAILURE = 'app/Videos/FETCH_VIDEOS_FAILURE';
const FETCH_VIDEOS_SUCCESS = 'app/Videos/FETCH_VIDEOS_SUCCESS';

// video dialog
const TOGGLE_VIDEO_DIALOG = 'TOGGLE_VIDEO_DIALOG';
// blog
const FETCH_BLOG_LIST = 'FETCH_BLOG_LIST';

// speakers
const FETCH_SPEAKERS = 'app/Speakers/FETCH_SPEAKERS';
const FETCH_SPEAKERS_FAILURE = 'app/Speakers/FETCH_SPEAKERS_FAILURE';
const FETCH_SPEAKERS_SUCCESS = 'app/Speakers/FETCH_SPEAKERS_SUCCESS';

const FETCH_SPEAKERS_LIST = 'FETCH_SPEAKERS_LIST';
const UPDATE_SPEAKERS = 'UPDATE_SPEAKERS';
// previous speakers
const FETCH_PREVIOUS_SPEAKERS_LIST = 'FETCH_PREVIOUS_SPEAKERS_LIST';
// sessions
const FETCH_SESSIONS = 'app/Sessions/FETCH_SESSIONS';
const FETCH_SESSIONS_FAILURE = 'app/Sessions/FETCH_SESSIONS_FAILURE';
const FETCH_SESSIONS_SUCCESS = 'app/Sessions/FETCH_SESSIONS_SUCCESS';

const FETCH_USER_FEATURED_SESSIONS = 'FETCH_USER_FEATURED_SESSIONS';
const SET_USER_FEATURED_SESSIONS = 'SET_USER_FEATURED_SESSIONS';
// schedule
const FETCH_SCHEDULE = 'app/Schedule/FETCH_SCHEDULE';
const FETCH_SCHEDULE_FAILURE = 'app/Schedule/FETCH_SCHEDULE_FAILURE';
const FETCH_SCHEDULE_SUCCESS = 'app/Schedule/FETCH_SCHEDULE_SUCCESS';

// gallery
const FETCH_GALLERY = 'app/Gallery/FETCH_GALLERY';
const FETCH_GALLERY_FAILURE = 'app/Gallery/FETCH_GALLERY_FAILURE';
const FETCH_GALLERY_SUCCESS = 'app/Gallery/FETCH_GALLERY_SUCCESS';

// team
const FETCH_TEAM = 'FETCH_TEAM';
// user
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
// subscribe
const SUBSCRIBE = 'SUBSCRIBE';
// notifications
const UPDATE_NOTIFICATIONS_STATUS = 'UPDATE_NOTIFICATIONS_STATUS';
const NOTIFICATIONS_STATUS = {
  GRANTED: 'granted',
  DENIED: 'denied',
  DEFAULT: 'default',
};
