const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
const SET_VIEWPORT_SIZE = 'SET_VIEWPORT_SIZE';
// router
const SET_ROUTE = 'SET_ROUTE';
const SET_HERO = 'SET_HERO';
// tickets
const FETCH_TICKETS = 'FETCH_TICKETS';
// partners
const FETCH_PARTNERS = 'FETCH_PARTNERS';
//blog
const FETCH_BLOG_LIST = 'FETCH_BLOG_LIST';
const FETCH_BLOG_POST = 'FETCH_BLOG_POST';
