import type { Theme } from './tokens';

// Paper surfaces, ink outlines and hard offset shadows. Accents: blue, red, yellow, green.
export const festival: Theme = {
  fonts: { display: 'unbounded', body: 'inter', mono: 'jetbrains-mono' },
  light: {
    primary: '#3557e6',
    onPrimary: '#ffffff',
    primaryContainer: '#dfe6ff',
    onPrimaryContainer: '#10236b',
    secondary: '#f6b400',
    onSecondary: '#1b1b1f',
    surface: '#fffdf7',
    surfaceDim: '#ece8dc',
    surfaceBright: '#ffffff',
    surfaceContainer: '#f4f1e8',
    surfaceContainerHigh: '#ebe7da',
    onSurface: '#1b1b1f',
    onSurfaceVariant: '#4a4a55',
    outline: '#6b6b76',
    outlineVariant: '#d6d2c4',
    ink: '#1b1b1f',
    focus: '#3557e6',
    error: '#c5221f',
    onError: '#ffffff',
    success: '#146c2e',
    scrim: 'rgb(27 27 31 / 55%)',
    accent1: '#3557e6',
    accent1Container: '#c9dbff',
    onAccent1Container: '#0f1f5c',
    accent2: '#d93025',
    accent2Container: '#ffd3cc',
    onAccent2Container: '#5c1009',
    accent3: '#f6b400',
    accent3Container: '#ffe7a3',
    onAccent3Container: '#4a3500',
    accent4: '#188038',
    accent4Container: '#c8efc9',
    onAccent4Container: '#0b3d19',
  },
  dark: {
    primary: '#9db4ff',
    onPrimary: '#0d1b4f',
    primaryContainer: '#22315f',
    onPrimaryContainer: '#dfe6ff',
    secondary: '#f7c948',
    onSecondary: '#1b1b1f',
    surface: '#18181c',
    surfaceDim: '#121215',
    surfaceBright: '#2a2a30',
    surfaceContainer: '#24242a',
    surfaceContainerHigh: '#2e2e35',
    onSurface: '#f2efe6',
    onSurfaceVariant: '#c4c2ba',
    outline: '#a09e96',
    outlineVariant: '#3d3d45',
    // Outlines and hard shadows turn light, so they stay visible on dark surfaces.
    ink: '#f2efe6',
    focus: '#9db4ff',
    error: '#ffb4ab',
    onError: '#690005',
    success: '#7dd88f',
    scrim: 'rgb(0 0 0 / 60%)',
    accent1: '#9db4ff',
    accent1Container: '#22315f',
    onAccent1Container: '#dfe6ff',
    accent2: '#ff8a7a',
    accent2Container: '#5c2621',
    onAccent2Container: '#ffdad5',
    accent3: '#f7c948',
    accent3Container: '#4d3d0f',
    onAccent3Container: '#ffe7a3',
    accent4: '#7dd88f',
    accent4Container: '#1f4424',
    onAccent4Container: '#c8efc9',
  },
  style: {
    radiusS: '8px',
    radiusM: '16px',
    radiusL: '28px',
    radiusAvatar: '38%',
    borderWidth: '2px',
    borderColor: 'var(--hb-color-ink)',
    shadowCard: '4px 4px 0 0 var(--hb-color-ink)',
    shadowCardHover: '6px 6px 0 0 var(--hb-color-ink)',
    shadowButton: '3px 3px 0 0 var(--hb-color-ink)',
    pressOffset: '3px',
    ctaBackground: 'var(--hb-color-primary)',
    onCta: 'var(--hb-color-on-primary)',
    // An ink band in light. In dark, ink is light, so the band uses a dim surface instead.
    footerBackground: 'light-dark(var(--hb-color-ink), var(--hb-color-surface-dim))',
    footerText: 'light-dark(var(--hb-color-surface), var(--hb-color-on-surface))',
    pageBackground: 'var(--hb-color-surface)',
    sectionBackground: 'var(--hb-color-surface)',
    tintOpacity: '100%',
    panelBackground: 'var(--hb-color-surface-bright)',
    barBackground: 'var(--hb-color-surface)',
    backdropFilter: 'none',
  },
};
