import type { Theme } from './tokens';

// Modeled on Apple's Liquid Glass: frosted, translucent panels over soft color glows, large round corners and system colors.
const glow = (accent: string, size: string, position: string, amount: string) =>
  `radial-gradient(${size} at ${position}, color-mix(in srgb, var(--hb-color-${accent}) ${amount}, transparent), transparent 70%) fixed`;

export const glass: Theme = {
  fonts: { display: 'inter', body: 'inter', mono: 'jetbrains-mono' },
  light: {
    primary: '#0066cc',
    onPrimary: '#ffffff',
    primaryContainer: '#d6e6ff',
    onPrimaryContainer: '#002f66',
    secondary: '#5e5ce6',
    onSecondary: '#ffffff',
    surface: '#f5f5f7',
    surfaceDim: '#e8e8ed',
    surfaceBright: '#ffffff',
    surfaceContainer: '#ededf2',
    surfaceContainerHigh: '#e3e3e8',
    onSurface: '#1d1d1f',
    onSurfaceVariant: '#636366',
    outline: '#86868b',
    outlineVariant: '#d2d2d7',
    ink: '#1d1d1f',
    focus: '#0066cc',
    error: '#d70015',
    onError: '#ffffff',
    success: '#248a3d',
    scrim: 'rgb(0 0 0 / 50%)',
    accent1: '#0066cc',
    accent1Container: '#d6e6ff',
    onAccent1Container: '#002f66',
    accent2: '#d30f45',
    accent2Container: '#ffd9e1',
    onAccent2Container: '#5c0019',
    accent3: '#ff9f0a',
    accent3Container: '#ffe8c7',
    onAccent3Container: '#4d2c00',
    accent4: '#34c759',
    accent4Container: '#d4f5dc',
    onAccent4Container: '#0b3d1a',
  },
  dark: {
    primary: '#4da3ff',
    onPrimary: '#00213f',
    primaryContainer: '#0a3a75',
    onPrimaryContainer: '#d6e6ff',
    secondary: '#8e8cff',
    onSecondary: '#14124a',
    surface: '#0b0b0f',
    surfaceDim: '#050507',
    surfaceBright: '#2c2c2e',
    surfaceContainer: '#1c1c1e',
    surfaceContainerHigh: '#26262a',
    onSurface: '#f5f5f7',
    onSurfaceVariant: '#aeaeb2',
    outline: '#8e8e93',
    outlineVariant: '#3a3a3c',
    ink: '#f5f5f7',
    focus: '#4da3ff',
    error: '#ff6961',
    onError: '#4d0004',
    success: '#30d158',
    scrim: 'rgb(0 0 0 / 60%)',
    accent1: '#4da3ff',
    accent1Container: '#0a3a75',
    onAccent1Container: '#d6e6ff',
    accent2: '#ff6482',
    accent2Container: '#5c1428',
    onAccent2Container: '#ffd9e1',
    accent3: '#ffb340',
    accent3Container: '#4d3000',
    onAccent3Container: '#ffe8c7',
    accent4: '#30d158',
    accent4Container: '#0e4220',
    onAccent4Container: '#d4f5dc',
  },
  style: {
    radiusS: '12px',
    radiusM: '22px',
    radiusL: '32px',
    radiusAvatar: '50%',
    borderWidth: '1px',
    borderColor: 'color-mix(in srgb, var(--hb-color-ink) 12%, transparent)',
    // A bright rim on the top edge, where the light hits the glass, over a soft shadow.
    shadowCard:
      'inset 0 1px 0 color-mix(in srgb, light-dark(var(--hb-color-surface-bright), var(--hb-color-on-surface)) 60%, transparent), 0 8px 32px color-mix(in srgb, var(--hb-color-scrim) 30%, transparent)',
    shadowCardHover:
      'inset 0 1px 0 color-mix(in srgb, light-dark(var(--hb-color-surface-bright), var(--hb-color-on-surface)) 70%, transparent), 0 14px 44px color-mix(in srgb, var(--hb-color-scrim) 40%, transparent)',
    shadowButton:
      'inset 0 1px 0 color-mix(in srgb, light-dark(var(--hb-color-surface-bright), var(--hb-color-on-surface)) 45%, transparent), 0 4px 16px color-mix(in srgb, var(--hb-color-scrim) 25%, transparent)',
    pressOffset: '0px',
    ctaBackground: 'var(--hb-color-primary)',
    onCta: 'var(--hb-color-on-primary)',
    footerBackground: 'color-mix(in srgb, var(--hb-color-surface-container) 70%, transparent)',
    footerText: 'var(--hb-color-on-surface)',
    pageBackground: [
      glow('accent-1', '60rem 40rem', '0% 0%', '30%'),
      glow('accent-2', '50rem 40rem', '100% 30%', '22%'),
      glow('accent-4', '60rem 45rem', '30% 100%', '22%'),
      'var(--hb-color-surface)',
    ].join(', '),
    sectionBackground: 'transparent',
    tintOpacity: '60%',
    panelBackground: 'color-mix(in srgb, var(--hb-color-surface-bright) 58%, transparent)',
    barBackground: 'color-mix(in srgb, var(--hb-color-surface) 72%, transparent)',
    backdropFilter: 'blur(20px) saturate(180%)',
  },
};
