import type { Theme } from './tokens';

// White paper, light pencil outlines and watercolor washes: ultramarine, rose madder, ochre, sap green.
export const paper: Theme = {
  fonts: { display: 'unbounded', body: 'inter', mono: 'jetbrains-mono' },
  light: {
    primary: '#3f5f9a',
    onPrimary: '#ffffff',
    primaryContainer: '#dde7f3',
    onPrimaryContainer: '#1c2f52',
    secondary: '#e3b25a',
    onSecondary: '#2f2f33',
    surface: '#fffefb',
    surfaceDim: '#ebe9e3',
    surfaceBright: '#ffffff',
    surfaceContainer: '#f7f6f2',
    surfaceContainerHigh: '#efede7',
    onSurface: '#2f2f33',
    onSurfaceVariant: '#5b5a60',
    outline: '#8a8780',
    outlineVariant: '#d3d0c8',
    ink: '#3c3b40',
    focus: '#3f5f9a',
    error: '#b3261e',
    onError: '#ffffff',
    success: '#3f7a3e',
    scrim: 'rgb(47 47 51 / 50%)',
    accent1: '#3f5f9a',
    accent1Container: '#dbe6f2',
    onAccent1Container: '#1c2f52',
    accent2: '#b8475a',
    accent2Container: '#f6dde1',
    onAccent2Container: '#5a1c28',
    accent3: '#d9a441',
    accent3Container: '#f8edd3',
    onAccent3Container: '#4d3a12',
    accent4: '#5b8a5a',
    accent4Container: '#dfecdb',
    onAccent4Container: '#23401f',
  },
  dark: {
    primary: '#9db6e0',
    onPrimary: '#142544',
    primaryContainer: '#263a5a',
    onPrimaryContainer: '#dde7f3',
    secondary: '#e8bf6e',
    onSecondary: '#1d1c1a',
    surface: '#1d1c1a',
    surfaceDim: '#161514',
    surfaceBright: '#2b2a27',
    surfaceContainer: '#252421',
    surfaceContainerHigh: '#2f2e2a',
    onSurface: '#ece9e2',
    onSurfaceVariant: '#c2beb5',
    outline: '#9a968d',
    outlineVariant: '#4a4843',
    ink: '#e6e2da',
    focus: '#9db6e0',
    error: '#ffb4ab',
    onError: '#690005',
    success: '#8fcf8c',
    scrim: 'rgb(0 0 0 / 60%)',
    accent1: '#9db6e0',
    accent1Container: '#263a5a',
    onAccent1Container: '#dde7f3',
    accent2: '#e79aa6',
    accent2Container: '#4f2530',
    onAccent2Container: '#f6dde1',
    accent3: '#e8bf6e',
    accent3Container: '#4a3a18',
    onAccent3Container: '#f8edd3',
    accent4: '#9cc79a',
    accent4Container: '#26402a',
    onAccent4Container: '#dfecdb',
  },
  style: {
    // Nearly square corners, a little uneven, as if drawn by hand. `radiusL` stays one length, because `calc()` reads it.
    radiusS: '1px 2px 1px 3px / 2px 1px 3px 1px',
    radiusM: '2px 3px 2px 4px / 3px 2px 4px 2px',
    radiusL: '3px',
    radiusAvatar: '47% 53% 45% 55% / 53% 46% 54% 47%',
    borderWidth: '1.5px',
    borderColor: 'var(--hb-color-outline-variant)',
    // A second, fainter pencil stroke just off the first.
    shadowCard: '1px 2px 0 -0.5px var(--hb-color-outline-variant)',
    shadowCardHover: '2px 4px 0 -0.5px var(--hb-color-outline-variant)',
    shadowButton: '1px 2px 0 -0.5px var(--hb-color-outline-variant)',
    pressOffset: '1px',
    ctaBackground: 'var(--hb-color-primary)',
    onCta: 'var(--hb-color-on-primary)',
    footerBackground: 'var(--hb-color-surface-container)',
    footerText: 'var(--hb-color-on-surface)',
  },
};
