import type { Theme } from './tokens';

// Inspired by DevFest for Ukraine: no outlines, soft glow shadows and one bright yellow accent.
export const spotlight: Theme = {
  fonts: { display: 'unbounded', body: 'inter', mono: 'jetbrains-mono' },
  light: {
    primary: '#2848c9',
    onPrimary: '#ffffff',
    primaryContainer: '#dce4ff',
    onPrimaryContainer: '#0b1a4a',
    secondary: '#f7d36b',
    onSecondary: '#15161a',
    surface: '#ffffff',
    surfaceDim: '#e9eaee',
    surfaceBright: '#ffffff',
    surfaceContainer: '#f3f4f7',
    surfaceContainerHigh: '#e8e9ee',
    onSurface: '#15161a',
    onSurfaceVariant: '#4b4d57',
    outline: '#767884',
    outlineVariant: '#d9dae0',
    ink: '#15161a',
    focus: '#2848c9',
    error: '#b3261e',
    onError: '#ffffff',
    success: '#146c2e',
    scrim: 'rgb(21 22 26 / 55%)',
    accent1: '#2848c9',
    accent1Container: '#dce4ff',
    onAccent1Container: '#0b1a4a',
    accent2: '#c2185b',
    accent2Container: '#ffd9e0',
    onAccent2Container: '#5a0a2a',
    accent3: '#f7d36b',
    accent3Container: '#fff1c2',
    onAccent3Container: '#4a3c10',
    accent4: '#0f7a5c',
    accent4Container: '#c9f2e6',
    onAccent4Container: '#0b3a2c',
  },
  dark: {
    primary: '#8fb0ff',
    onPrimary: '#0b1a4a',
    primaryContainer: '#1f2c55',
    onPrimaryContainer: '#dce4ff',
    secondary: '#f7d36b',
    onSecondary: '#15161a',
    surface: '#15161a',
    surfaceDim: '#0f1013',
    surfaceBright: '#26272d',
    surfaceContainer: '#202126',
    surfaceContainerHigh: '#2a2b31',
    onSurface: '#ecedf1',
    onSurfaceVariant: '#b8bac4',
    outline: '#8b8d97',
    outlineVariant: '#3a3b42',
    ink: '#ecedf1',
    focus: '#f7d36b',
    error: '#ffb4ab',
    onError: '#690005',
    success: '#7dd88f',
    scrim: 'rgb(0 0 0 / 65%)',
    accent1: '#8fb0ff',
    accent1Container: '#1f2c55',
    onAccent1Container: '#dce4ff',
    accent2: '#ff8fa3',
    accent2Container: '#561d2a',
    onAccent2Container: '#ffd9e0',
    accent3: '#f7d36b',
    accent3Container: '#4a3c10',
    onAccent3Container: '#ffe9a8',
    accent4: '#7fdcc0',
    accent4Container: '#12443a',
    onAccent4Container: '#c9f2e6',
  },
  style: {
    radiusS: '10px',
    radiusM: '18px',
    radiusL: '28px',
    radiusAvatar: '50%',
    borderWidth: '1px',
    borderColor: 'var(--hb-color-outline-variant)',
    shadowCard: '0 8px 24px color-mix(in srgb, var(--hb-color-primary) 16%, transparent)',
    shadowCardHover: '0 14px 36px color-mix(in srgb, var(--hb-color-primary) 26%, transparent)',
    shadowButton: '0 4px 14px color-mix(in srgb, var(--hb-color-primary) 30%, transparent)',
    pressOffset: '0px',
    ctaBackground: 'var(--hb-color-secondary)',
    onCta: 'var(--hb-color-on-secondary)',
    footerBackground: 'var(--hb-color-surface-container)',
    footerText: 'var(--hb-color-on-surface)',
    pageBackground: 'var(--hb-color-surface)',
    sectionBackground: 'var(--hb-color-surface)',
    tintOpacity: '100%',
    panelBackground: 'var(--hb-color-surface-bright)',
    barBackground: 'var(--hb-color-surface)',
    backdropFilter: 'none',
  },
};
