(function(n,C){var x=n.GreenSockGlobals=n.GreenSockGlobals||n;if(!x.TweenLite){var t,p,c,m,q,w=function(b){var a=b.split("."),d=x;for(b=0;a.length>b;b++)d[a[b]]=d=d[a[b]]||{};return d},r=w("com.greensock"),y=function(b){var a,d=[],e=b.length;for(a=0;a!==e;d.push(b[a++]));return d},v=function(){},z=function(){var b=Object.prototype.toString,a=b.call([]);return function(d){return null!=d&&(d instanceof Array||"object"==typeof d&&!!d.push&&b.call(d)===a)}}(),B={},h=function(b,a,d,e){this.sc=B[b]?B[b].sc:
[];B[b]=this;this.gsClass=null;this.func=d;var l=[];this.check=function(u){for(var c,g,f=a.length,s=f;-1<--f;)(c=B[a[f]]||new h(a[f],[])).gsClass?(l[f]=c.gsClass,s--):u&&c.sc.push(this);if(0===s&&d)for(u=("com.greensock."+b).split("."),c=u.pop(),g=w(u.join("."))[c]=this.gsClass=d.apply(d,l),e&&(x[c]=g,"function"==typeof define&&define.amd?define((n.GreenSockAMDPath?n.GreenSockAMDPath+"/":"")+b.split(".").pop(),[],function(){return g}):b===C&&"undefined"!=typeof module&&module.exports&&(module.exports=
g)),f=0;this.sc.length>f;f++)this.sc[f].check()};this.check(!0)},a=n._gsDefine=function(b,a,d,e){return new h(b,a,d,e)},f=r._class=function(b,H,d){return H=H||function(){},a(b,[],function(){return H},d),H};a.globals=x;var s=[0,0,1,1],S=[],D=f("easing.Ease",function(b,a,d,e){this._func=b;this._type=d||0;this._power=e||0;this._params=a?s.concat(a):s},!0),N=D.map={},I=D.register=function(b,a,d,e){var l,u,c;a=a.split(",");for(var g=a.length,h=(d||"easeIn,easeOut,easeInOut").split(",");-1<--g;)for(l=a[g],
d=e?f("easing."+l,null,!0):r.easing[l]||{},u=h.length;-1<--u;)c=h[u],N[l+"."+c]=N[c+l]=d[c]=b.getRatio?b:b[c]||new b};c=D.prototype;c._calcEnd=!1;c.getRatio=function(b){if(this._func)return this._params[0]=b,this._func.apply(null,this._params);var a=this._type,d=this._power,e=1===a?1-b:2===a?b:.5>b?2*b:2*(1-b);return 1===d?e*=e:2===d?e*=e*e:3===d?e*=e*e*e:4===d&&(e*=e*e*e*e),1===a?1-e:2===a?e:.5>b?e/2:1-e/2};t=["Linear","Quad","Cubic","Quart","Quint,Strong"];for(p=t.length;-1<--p;)c=t[p]+",Power"+
p,I(new D(null,null,1,p),c,"easeOut",!0),I(new D(null,null,2,p),c,"easeIn"+(0===p?",easeNone":"")),I(new D(null,null,3,p),c,"easeInOut");N.linear=r.easing.Linear.easeIn;N.swing=r.easing.Quad.easeInOut;var Y=f("events.EventDispatcher",function(b){this._listeners={};this._eventTarget=b||this});c=Y.prototype;c.addEventListener=function(b,a,d,e,l){l=l||0;var u,c=this._listeners[b],g=0;null==c&&(this._listeners[b]=c=[]);for(u=c.length;-1<--u;)b=c[u],b.c===a&&b.s===d?c.splice(u,1):0===g&&l>b.pr&&(g=u+1);
c.splice(g,0,{c:a,s:d,up:e,pr:l});this!==m||q||m.wake()};c.removeEventListener=function(b,a){var d,e=this._listeners[b];if(e)for(d=e.length;-1<--d;)if(e[d].c===a)return e.splice(d,1),void 0};c.dispatchEvent=function(b){var a,d,e,l=this._listeners[b];if(l)for(a=l.length,d=this._eventTarget;-1<--a;)e=l[a],e.up?e.c.call(e.s||d,{type:b,target:d}):e.c.call(e.s||d)};var O=n.requestAnimationFrame,T=n.cancelAnimationFrame,P=Date.now||function(){return(new Date).getTime()},M=P();t=["ms","moz","webkit","o"];
for(p=t.length;-1<--p&&!O;)O=n[t[p]+"RequestAnimationFrame"],T=n[t[p]+"CancelAnimationFrame"]||n[t[p]+"CancelRequestAnimationFrame"];f("Ticker",function(b,a){var d,e,l,u,c,g=this,f=P(),h=!1!==a&&O,s=500,k=33,n=function(b){var a,H;a=P()-M;a>s&&(f+=a-k);M+=a;g.time=(M-f)/1E3;a=g.time-c;(!d||0<a||!0===b)&&(g.frame++,c+=a+(a>=u?.004:u-a),H=!0);!0!==b&&(l=e(n));H&&g.dispatchEvent("tick")};Y.call(g);g.time=g.frame=0;g.tick=function(){n(!0)};g.lagSmoothing=function(b,a){s=b||1E10;k=Math.min(a,s,0)};g.sleep=
function(){null!=l&&(h&&T?T(l):clearTimeout(l),e=v,l=null,g===m&&(q=!1))};g.wake=function(){null!==l?g.sleep():10<g.frame&&(M=P()-s+5);e=0===d?v:h&&O?O:function(b){return setTimeout(b,0|1E3*(c-g.time)+1)};g===m&&(q=!0);n(2)};g.fps=function(b){return arguments.length?(d=b,u=1/(d||60),c=this.time+u,g.wake(),void 0):d};g.useRAF=function(b){return arguments.length?(g.sleep(),h=b,g.fps(d),void 0):h};g.fps(b);setTimeout(function(){h&&(!l||5>g.frame)&&g.useRAF(!1)},1500)});c=r.Ticker.prototype=new r.events.EventDispatcher;
c.constructor=r.Ticker;var A=f("core.Animation",function(b,a){if(this.vars=a=a||{},this._duration=this._totalDuration=b||0,this._delay=Number(a.delay)||0,this._timeScale=1,this._active=!0===a.immediateRender,this.data=a.data,this._reversed=!0===a.reversed,F){q||m.wake();var d=this.vars.useFrames?J:F;d.add(this,d._time);this.vars.paused&&this.paused(!0)}});m=A.ticker=new r.Ticker;c=A.prototype;c._dirty=c._gc=c._initted=c._paused=!1;c._totalTime=c._time=0;c._rawPrevTime=-1;c._next=c._last=c._onUpdate=
c._timeline=c.timeline=null;c._paused=!1;var Z=function(){q&&2E3<P()-M&&m.wake();setTimeout(Z,2E3)};Z();c.play=function(b,a){return null!=b&&this.seek(b,a),this.reversed(!1).paused(!1)};c.pause=function(b,a){return null!=b&&this.seek(b,a),this.paused(!0)};c.resume=function(b,a){return null!=b&&this.seek(b,a),this.paused(!1)};c.seek=function(b,a){return this.totalTime(Number(b),!1!==a)};c.restart=function(b,a){return this.reversed(!1).paused(!1).totalTime(b?-this._delay:0,!1!==a,!0)};c.reverse=function(b,
a){return null!=b&&this.seek(b||this.totalDuration(),a),this.reversed(!0).paused(!1)};c.render=function(){};c.invalidate=function(){return this};c.isActive=function(){var b,a=this._timeline,d=this._startTime;return!a||!this._gc&&!this._paused&&a.isActive()&&(b=a.rawTime())>=d&&d+this.totalDuration()/this._timeScale>b};c._enabled=function(b,a){return q||m.wake(),this._gc=!b,this._active=this.isActive(),!0!==a&&(b&&!this.timeline?this._timeline.add(this,this._startTime-this._delay):!b&&this.timeline&&
this._timeline._remove(this,!0)),!1};c._kill=function(){return this._enabled(!1,!1)};c.kill=function(b,a){return this._kill(b,a),this};c._uncache=function(b){for(b=b?this:this.timeline;b;)b._dirty=!0,b=b.timeline;return this};c._swapSelfInParams=function(b){for(var a=b.length,d=b.concat();-1<--a;)"{self}"===b[a]&&(d[a]=this);return d};c.eventCallback=function(b,a,d,e){if("on"===(b||"").substr(0,2)){var l=this.vars;if(1===arguments.length)return l[b];null==a?delete l[b]:(l[b]=a,l[b+"Params"]=z(d)&&
-1!==d.join("").indexOf("{self}")?this._swapSelfInParams(d):d,l[b+"Scope"]=e);"onUpdate"===b&&(this._onUpdate=a)}return this};c.delay=function(b){return arguments.length?(this._timeline.smoothChildTiming&&this.startTime(this._startTime+b-this._delay),this._delay=b,this):this._delay};c.duration=function(b){return arguments.length?(this._duration=this._totalDuration=b,this._uncache(!0),this._timeline.smoothChildTiming&&0<this._time&&this._time<this._duration&&0!==b&&this.totalTime(b/this._duration*
this._totalTime,!0),this):(this._dirty=!1,this._duration)};c.totalDuration=function(b){return this._dirty=!1,arguments.length?this.duration(b):this._totalDuration};c.time=function(b,a){return arguments.length?(this._dirty&&this.totalDuration(),this.totalTime(b>this._duration?this._duration:b,a)):this._time};c.totalTime=function(b,a,d){if(q||m.wake(),!arguments.length)return this._totalTime;if(this._timeline){if(0>b&&!d&&(b+=this.totalDuration()),this._timeline.smoothChildTiming){this._dirty&&this.totalDuration();
var e=this._totalDuration,l=this._timeline;if(b>e&&!d&&(b=e),this._startTime=(this._paused?this._pauseTime:l._time)-(this._reversed?e-b:b)/this._timeScale,l._dirty||this._uncache(!1),l._timeline)for(;l._timeline;)l._timeline._time!==(l._startTime+l._totalTime)/l._timeScale&&l.totalTime(l._totalTime,!0),l=l._timeline}this._gc&&this._enabled(!0,!1);(this._totalTime!==b||0===this._duration)&&(this.render(b,a,!1),G.length&&Q())}return this};c.progress=c.totalProgress=function(b,a){return arguments.length?
this.totalTime(this.duration()*b,a):this._time/this.duration()};c.startTime=function(b){return arguments.length?(b!==this._startTime&&(this._startTime=b,this.timeline&&this.timeline._sortChildren&&this.timeline.add(this,b-this._delay)),this):this._startTime};c.timeScale=function(b){if(!arguments.length)return this._timeScale;if(b=b||1E-10,this._timeline&&this._timeline.smoothChildTiming){var a=this._pauseTime,a=a||0===a?a:this._timeline.totalTime();this._startTime=a-(a-this._startTime)*this._timeScale/
b}return this._timeScale=b,this._uncache(!1)};c.reversed=function(b){return arguments.length?(b!=this._reversed&&(this._reversed=b,this.totalTime(this._timeline&&!this._timeline.smoothChildTiming?this.totalDuration()-this._totalTime:this._totalTime,!0)),this):this._reversed};c.paused=function(b){if(!arguments.length)return this._paused;if(b!=this._paused&&this._timeline){q||b||m.wake();var a=this._timeline,d=a.rawTime(),e=d-this._pauseTime;!b&&a.smoothChildTiming&&(this._startTime+=e,this._uncache(!1));
this._pauseTime=b?d:null;this._paused=b;this._active=this.isActive();!b&&0!==e&&this._initted&&this.duration()&&this.render(a.smoothChildTiming?this._totalTime:(d-this._startTime)/this._timeScale,!0,!0)}return this._gc&&!b&&this._enabled(!0,!1),this};p=f("core.SimpleTimeline",function(b){A.call(this,0,b);this.autoRemoveChildren=this.smoothChildTiming=!0});c=p.prototype=new A;c.constructor=p;c.kill()._gc=!1;c._first=c._last=null;c._sortChildren=!1;c.add=c.insert=function(b,a){var d,e;if(b._startTime=
Number(a||0)+b._delay,b._paused&&this!==b._timeline&&(b._pauseTime=b._startTime+(this.rawTime()-b._startTime)/b._timeScale),b.timeline&&b.timeline._remove(b,!0),b.timeline=b._timeline=this,b._gc&&b._enabled(!0,!0),d=this._last,this._sortChildren)for(e=b._startTime;d&&d._startTime>e;)d=d._prev;return d?(b._next=d._next,d._next=b):(b._next=this._first,this._first=b),b._next?b._next._prev=b:this._last=b,b._prev=d,this._timeline&&this._uncache(!0),this};c._remove=function(b,a){return b.timeline===this&&
(a||b._enabled(!1,!0),b._prev?b._prev._next=b._next:this._first===b&&(this._first=b._next),b._next?b._next._prev=b._prev:this._last===b&&(this._last=b._prev),b._next=b._prev=b.timeline=null,this._timeline&&this._uncache(!0)),this};c.render=function(b,a,d){var e,l=this._first;for(this._totalTime=this._time=this._rawPrevTime=b;l;)e=l._next,(l._active||b>=l._startTime&&!l._paused)&&(l._reversed?l.render((l._dirty?l.totalDuration():l._totalDuration)-(b-l._startTime)*l._timeScale,a,d):l.render((b-l._startTime)*
l._timeScale,a,d)),l=e};c.rawTime=function(){return q||m.wake(),this._totalTime};var k=f("TweenLite",function(b,a,d){if(A.call(this,a,d),this.render=k.prototype.render,null==b)throw"Cannot tween a null target.";this.target=b="string"!=typeof b?b:k.selector(b)||b;var e,l;e=b.jquery||b.length&&b!==n&&b[0]&&(b[0]===n||b[0].nodeType&&b[0].style&&!b.nodeType);d=this.vars.overwrite;if(this._overwrite=d=null==d?$[k.defaultOverwrite]:"number"==typeof d?d>>0:$[d],(e||b instanceof Array||b.push&&z(b))&&"number"!=
typeof b[0])for(this._targets=l=y(b),this._propLookup=[],this._siblings=[],b=0;l.length>b;b++)(e=l[b])?"string"!=typeof e?e.length&&e!==n&&e[0]&&(e[0]===n||e[0].nodeType&&e[0].style&&!e.nodeType)?(l.splice(b--,1),this._targets=l=l.concat(y(e))):(this._siblings[b]=R(e,this,!1),1===d&&1<this._siblings[b].length&&U(e,this,null,1,this._siblings[b])):(e=l[b--]=k.selector(e),"string"==typeof e&&l.splice(b+1,1)):l.splice(b--,1);else this._propLookup={},this._siblings=R(b,this,!1),1===d&&1<this._siblings.length&&
U(b,this,null,1,this._siblings);(this.vars.immediateRender||0===a&&0===this._delay&&!1!==this.vars.immediateRender)&&(this._time=-1E-10,this.render(-this._delay))},!0),V=function(b){return b.length&&b!==n&&b[0]&&(b[0]===n||b[0].nodeType&&b[0].style&&!b.nodeType)};c=k.prototype=new A;c.constructor=k;c.kill()._gc=!1;c.ratio=0;c._firstPT=c._targets=c._overwrittenProps=c._startAt=null;c._notifyPluginsOfEnabled=c._lazy=!1;k.version="1.13.1";k.defaultEase=c._ease=new D(null,null,1,1);k.defaultOverwrite=
"auto";k.ticker=m;k.autoSleep=!0;k.lagSmoothing=function(b,a){m.lagSmoothing(b,a)};k.selector=n.$||n.jQuery||function(b){var a=n.$||n.jQuery;return a?(k.selector=a,a(b)):"undefined"==typeof document?b:document.querySelectorAll?document.querySelectorAll(b):document.getElementById("#"===b.charAt(0)?b.substr(1):b)};var G=[],W={},I=k._internals={isArray:z,isSelector:V,lazyTweens:G},K=k._plugins={},L=I.tweenLookup={},ba=0,X=I.reservedProps={ease:1,delay:1,overwrite:1,onComplete:1,onCompleteParams:1,onCompleteScope:1,
useFrames:1,runBackwards:1,startAt:1,onUpdate:1,onUpdateParams:1,onUpdateScope:1,onStart:1,onStartParams:1,onStartScope:1,onReverseComplete:1,onReverseCompleteParams:1,onReverseCompleteScope:1,onRepeat:1,onRepeatParams:1,onRepeatScope:1,easeParams:1,yoyo:1,immediateRender:1,repeat:1,repeatDelay:1,data:1,paused:1,reversed:1,autoCSS:1,lazy:1},$={none:0,all:1,auto:2,concurrent:3,allOnStart:4,preexisting:5,"true":1,"false":0},J=A._rootFramesTimeline=new p,F=A._rootTimeline=new p,Q=I.lazyRender=function(){var b=
G.length;for(W={};-1<--b;)(t=G[b])&&!1!==t._lazy&&(t.render(t._lazy,!1,!0),t._lazy=!1);G.length=0};F._startTime=m.time;J._startTime=m.frame;F._active=J._active=!0;setTimeout(Q,1);A._updateRoot=k.render=function(){var b,a,d;if(G.length&&Q(),F.render((m.time-F._startTime)*F._timeScale,!1,!1),J.render((m.frame-J._startTime)*J._timeScale,!1,!1),G.length&&Q(),!(m.frame%120)){for(d in L){a=L[d].tweens;for(b=a.length;-1<--b;)a[b]._gc&&a.splice(b,1);0===a.length&&delete L[d]}if(d=F._first,(!d||d._paused)&&
k.autoSleep&&!J._first&&1===m._listeners.tick.length){for(;d&&d._paused;)d=d._next;d||m.sleep()}}};m.addEventListener("tick",A._updateRoot);var R=function(b,a,d){var e,l,c=b._gsTweenID;if(L[c||(b._gsTweenID=c="t"+ba++)]||(L[c]={target:b,tweens:[]}),a&&(e=L[c].tweens,e[l=e.length]=a,d))for(;-1<--l;)e[l]===a&&e.splice(l,1);return L[c].tweens},U=function(b,a,d,e,l){var c,f,g;if(1===e||4<=e){b=l.length;for(c=0;b>c;c++)if((g=l[c])!==a)g._gc||g._enabled(!1,!1)&&(f=!0);else if(5===e)break;return f}var h,
s=a._startTime+1E-10,k=[],n=0,m=0===a._duration;for(c=l.length;-1<--c;)(g=l[c])===a||g._gc||g._paused||(g._timeline!==a._timeline?(h=h||aa(a,0,m),0===aa(g,h,m)&&(k[n++]=g)):s>=g._startTime&&g._startTime+g.totalDuration()/g._timeScale>s&&((m||!g._initted)&&2E-10>=s-g._startTime||(k[n++]=g)));for(c=n;-1<--c;)g=k[c],2===e&&g._kill(d,b)&&(f=!0),(2!==e||!g._firstPT&&g._initted)&&g._enabled(!1,!1)&&(f=!0);return f},aa=function(b,a,d){for(var e=b._timeline,c=e._timeScale,u=b._startTime;e._timeline;){if(u+=
e._startTime,c*=e._timeScale,e._paused)return-100;e=e._timeline}return u/=c,u>a?u-a:d&&u===a||!b._initted&&2E-10>u-a?1E-10:(u+=b.totalDuration()/b._timeScale/c)>a+1E-10?0:u-a-1E-10};c._init=function(){var b,a,d,e=this.vars,c=this._overwrittenProps,u=this._duration,f=!!e.immediateRender,g=e.ease;if(e.startAt){this._startAt&&(this._startAt.render(-1,!0),this._startAt.kill());d={};for(b in e.startAt)d[b]=e.startAt[b];if(d.overwrite=!1,d.immediateRender=!0,d.lazy=f&&!1!==e.lazy,d.startAt=d.delay=null,
this._startAt=k.to(this.target,0,d),f)if(0<this._time)this._startAt=null;else if(0!==u)return}else if(e.runBackwards&&0!==u)if(this._startAt)this._startAt.render(-1,!0),this._startAt.kill(),this._startAt=null;else{d={};for(b in e)X[b]&&"autoCSS"!==b||(d[b]=e[b]);if(d.overwrite=0,d.data="isFromStart",d.lazy=f&&!1!==e.lazy,d.immediateRender=f,this._startAt=k.to(this.target,0,d),f){if(0===this._time)return}else this._startAt._init(),this._startAt._enabled(!1)}if(this._ease=g=g?g instanceof D?g:"function"==
typeof g?new D(g,e.easeParams):N[g]||k.defaultEase:k.defaultEase,e.easeParams instanceof Array&&g.config&&(this._ease=g.config.apply(g,e.easeParams)),this._easeType=this._ease._type,this._easePower=this._ease._power,this._firstPT=null,this._targets)for(b=this._targets.length;-1<--b;)this._initProps(this._targets[b],this._propLookup[b]={},this._siblings[b],c?c[b]:null)&&(a=!0);else a=this._initProps(this.target,this._propLookup,this._siblings,c);if(a&&k._onPluginEvent("_onInitAllProps",this),c&&(this._firstPT||
"function"!=typeof this.target&&this._enabled(!1,!1)),e.runBackwards)for(d=this._firstPT;d;)d.s+=d.c,d.c=-d.c,d=d._next;this._onUpdate=e.onUpdate;this._initted=!0};c._initProps=function(b,a,d,e){var c,f,h,g,s;if(null==b)return!1;W[b._gsTweenID]&&Q();if(!this.vars.css&&b.style&&b!==n&&b.nodeType&&K.css&&!1!==this.vars.autoCSS){f=this.vars;var k,m={};for(k in f)X[k]||k in b&&"transform"!==k&&"x"!==k&&"y"!==k&&"width"!==k&&"height"!==k&&"className"!==k&&"border"!==k||!(!K[k]||K[k]&&K[k]._autoCSS)||(m[k]=
f[k],delete f[k]);f.css=m}for(c in this.vars){if(f=this.vars[c],X[c])f&&(f instanceof Array||f.push&&z(f))&&-1!==f.join("").indexOf("{self}")&&(this.vars[c]=this._swapSelfInParams(f,this));else if(K[c]&&(g=new K[c])._onInitTween(b,this.vars[c],this)){this._firstPT=s={_next:this._firstPT,t:g,p:"setRatio",s:0,c:1,f:!0,n:c,pg:!0,pr:g._priority};for(f=g._overwriteProps.length;-1<--f;)a[g._overwriteProps[f]]=this._firstPT;(g._priority||g._onInitAllProps)&&(h=!0);(g._onDisable||g._onEnable)&&(this._notifyPluginsOfEnabled=
!0)}else this._firstPT=a[c]=s={_next:this._firstPT,t:b,p:c,f:"function"==typeof b[c],n:c,pg:!1,pr:0},s.s=s.f?b[c.indexOf("set")||"function"!=typeof b["get"+c.substr(3)]?c:"get"+c.substr(3)]():parseFloat(b[c]),s.c="string"==typeof f&&"="===f.charAt(1)?parseInt(f.charAt(0)+"1",10)*Number(f.substr(2)):Number(f)-s.s||0;s&&s._next&&(s._next._prev=s)}return e&&this._kill(e,b)?this._initProps(b,a,d,e):1<this._overwrite&&this._firstPT&&1<d.length&&U(b,this,a,this._overwrite,d)?(this._kill(a,b),this._initProps(b,
a,d,e)):(this._firstPT&&(!1!==this.vars.lazy&&this._duration||this.vars.lazy&&!this._duration)&&(W[b._gsTweenID]=!0),h)};c.render=function(b,a,d){var e,c,f,s,g=this._time,h=this._duration;f=this._rawPrevTime;if(b>=h)this._totalTime=this._time=h,this.ratio=this._ease._calcEnd?this._ease.getRatio(1):1,this._reversed||(e=!0,c="onComplete"),0===h&&(this._initted||!this.vars.lazy||d)&&(this._startTime===this._timeline._duration&&(b=0),(0===b||0>f||1E-10===f)&&f!==b&&(d=!0,1E-10<f&&(c="onReverseComplete")),
this._rawPrevTime=s=!a||b||f===b?b:1E-10);else if(1E-7>b)this._totalTime=this._time=0,this.ratio=this._ease._calcEnd?this._ease.getRatio(0):0,(0!==g||0===h&&0<f&&1E-10!==f)&&(c="onReverseComplete",e=this._reversed),0>b?(this._active=!1,0===h&&(this._initted||!this.vars.lazy||d)&&(0<=f&&(d=!0),this._rawPrevTime=s=!a||b||f===b?b:1E-10)):this._initted||(d=!0);else if(this._totalTime=this._time=b,this._easeType){var k=b/h,n=this._easeType,m=this._easePower;(1===n||3===n&&.5<=k)&&(k=1-k);3===n&&(k*=2);
1===m?k*=k:2===m?k*=k*k:3===m?k*=k*k*k:4===m&&(k*=k*k*k*k);this.ratio=1===n?1-k:2===n?k:.5>b/h?k/2:1-k/2}else this.ratio=this._ease.getRatio(b/h);if(this._time!==g||d){if(!this._initted){if(this._init(),!this._initted||this._gc)return;if(!d&&this._firstPT&&(!1!==this.vars.lazy&&this._duration||this.vars.lazy&&!this._duration))return this._time=this._totalTime=g,this._rawPrevTime=f,G.push(this),this._lazy=b,void 0;this._time&&!e?this.ratio=this._ease.getRatio(this._time/h):e&&this._ease._calcEnd&&
(this.ratio=this._ease.getRatio(0===this._time?0:1))}!1!==this._lazy&&(this._lazy=!1);this._active||!this._paused&&this._time!==g&&0<=b&&(this._active=!0);0!==g||(this._startAt&&(0<=b?this._startAt.render(b,a,d):c||(c="_dummyGS")),!this.vars.onStart||0===this._time&&0!==h||!a&&this.vars.onStart.apply(this.vars.onStartScope||this,this.vars.onStartParams||S));for(f=this._firstPT;f;)f.f?f.t[f.p](f.c*this.ratio+f.s):f.t[f.p]=f.c*this.ratio+f.s,f=f._next;this._onUpdate&&(0>b&&this._startAt&&this._startTime&&
this._startAt.render(b,a,d),a||(this._time!==g||e)&&this._onUpdate.apply(this.vars.onUpdateScope||this,this.vars.onUpdateParams||S));c&&(!this._gc||d)&&(0>b&&this._startAt&&!this._onUpdate&&this._startTime&&this._startAt.render(b,a,d),e&&(this._timeline.autoRemoveChildren&&this._enabled(!1,!1),this._active=!1),!a&&this.vars[c]&&this.vars[c].apply(this.vars[c+"Scope"]||this,this.vars[c+"Params"]||S),0===h&&1E-10===this._rawPrevTime&&1E-10!==s&&(this._rawPrevTime=0))}};c._kill=function(b,a){if("all"===
b&&(b=null),null==b&&(null==a||a===this.target))return this._lazy=!1,this._enabled(!1,!1);a="string"!=typeof a?a||this._targets||this.target:k.selector(a)||a;var d,e,c,f,h,g,s;if((z(a)||V(a))&&"number"!=typeof a[0])for(d=a.length;-1<--d;)this._kill(b,a[d])&&(g=!0);else{if(this._targets)for(d=this._targets.length;-1<--d;){if(a===this._targets[d]){h=this._propLookup[d]||{};this._overwrittenProps=this._overwrittenProps||[];e=this._overwrittenProps[d]=b?this._overwrittenProps[d]||{}:"all";break}}else{if(a!==
this.target)return!1;h=this._propLookup;e=this._overwrittenProps=b?this._overwrittenProps||{}:"all"}if(h){d=b||h;s=b!==e&&"all"!==e&&b!==h&&("object"!=typeof b||!b._tempKill);for(c in d)(f=h[c])&&(f.pg&&f.t._kill(d)&&(g=!0),f.pg&&0!==f.t._overwriteProps.length||(f._prev?f._prev._next=f._next:f===this._firstPT&&(this._firstPT=f._next),f._next&&(f._next._prev=f._prev),f._next=f._prev=null),delete h[c]),s&&(e[c]=1);!this._firstPT&&this._initted&&this._enabled(!1,!1)}}return g};c.invalidate=function(){return this._notifyPluginsOfEnabled&&
k._onPluginEvent("_onDisable",this),this._firstPT=null,this._overwrittenProps=null,this._onUpdate=null,this._startAt=null,this._initted=this._active=this._notifyPluginsOfEnabled=this._lazy=!1,this._propLookup=this._targets?{}:[],this};c._enabled=function(a,c){if(q||m.wake(),a&&this._gc){var d,e=this._targets;if(e)for(d=e.length;-1<--d;)this._siblings[d]=R(e[d],this,!0);else this._siblings=R(this.target,this,!0)}return A.prototype._enabled.call(this,a,c),this._notifyPluginsOfEnabled&&this._firstPT?
k._onPluginEvent(a?"_onEnable":"_onDisable",this):!1};k.to=function(a,c,d){return new k(a,c,d)};k.from=function(a,c,d){return d.runBackwards=!0,d.immediateRender=0!=d.immediateRender,new k(a,c,d)};k.fromTo=function(a,c,d,e){return e.startAt=d,e.immediateRender=0!=e.immediateRender&&0!=d.immediateRender,new k(a,c,e)};k.delayedCall=function(a,c,d,e,f){return new k(c,0,{delay:a,onComplete:c,onCompleteParams:d,onCompleteScope:e,onReverseComplete:c,onReverseCompleteParams:d,onReverseCompleteScope:e,immediateRender:!1,
useFrames:f,overwrite:0})};k.set=function(a,c){return new k(a,0,c)};k.getTweensOf=function(a,c){if(null==a)return[];a="string"!=typeof a?a:k.selector(a)||a;var d,e,f,h;if((z(a)||V(a))&&"number"!=typeof a[0]){d=a.length;for(e=[];-1<--d;)e=e.concat(k.getTweensOf(a[d],c));for(d=e.length;-1<--d;)for(h=e[d],f=d;-1<--f;)h===e[f]&&e.splice(d,1)}else for(e=R(a).concat(),d=e.length;-1<--d;)(e[d]._gc||c&&!e[d].isActive())&&e.splice(d,1);return e};k.killTweensOf=k.killDelayedCallsTo=function(a,c,d){"object"==
typeof c&&(d=c,c=!1);c=k.getTweensOf(a,c);for(var e=c.length;-1<--e;)c[e]._kill(d,a)};var E=f("plugins.TweenPlugin",function(a,c){this._overwriteProps=(a||"").split(",");this._propName=this._overwriteProps[0];this._priority=c||0;this._super=E.prototype},!0);if(c=E.prototype,E.version="1.10.1",E.API=2,c._firstPT=null,c._addTween=function(a,c,d,e,f,h){var k,g;return null!=e&&(k="number"==typeof e||"="!==e.charAt(1)?Number(e)-d:parseInt(e.charAt(0)+"1",10)*Number(e.substr(2)))?(this._firstPT=g={_next:this._firstPT,
t:a,p:c,s:d,c:k,f:"function"==typeof a[c],n:f||c,r:h},g._next&&(g._next._prev=g),g):void 0},c.setRatio=function(a){for(var c,d=this._firstPT;d;)c=d.c*a+d.s,d.r?c=Math.round(c):1E-6>c&&-1E-6<c&&(c=0),d.f?d.t[d.p](c):d.t[d.p]=c,d=d._next},c._kill=function(a){var c,d=this._overwriteProps,e=this._firstPT;if(null!=a[this._propName])this._overwriteProps=[];else for(c=d.length;-1<--c;)null!=a[d[c]]&&d.splice(c,1);for(;e;)null!=a[e.n]&&(e._next&&(e._next._prev=e._prev),e._prev?(e._prev._next=e._next,e._prev=
null):this._firstPT===e&&(this._firstPT=e._next)),e=e._next;return!1},c._roundProps=function(a,c){for(var d=this._firstPT;d;)(a[this._propName]||null!=d.n&&a[d.n.split(this._propName+"_").join("")])&&(d.r=c),d=d._next},k._onPluginEvent=function(a,c){var d,e,f,h,k,g=c._firstPT;if("_onInitAllProps"===a){for(;g;){k=g._next;for(e=f;e&&e.pr>g.pr;)e=e._next;(g._prev=e?e._prev:h)?g._prev._next=g:f=g;(g._next=e)?e._prev=g:h=g;g=k}g=c._firstPT=f}for(;g;)g.pg&&"function"==typeof g.t[a]&&g.t[a]()&&(d=!0),g=
g._next;return d},E.activate=function(a){for(var c=a.length;-1<--c;)a[c].API===E.API&&(K[(new a[c])._propName]=a[c]);return!0},a.plugin=function(a){if(!(a&&a.propName&&a.init&&a.API))throw"illegal plugin definition.";var c,d=a.propName,e=a.priority||0,h=a.overwriteProps,k={init:"_onInitTween",set:"setRatio",kill:"_kill",round:"_roundProps",initAll:"_onInitAllProps"},s=f("plugins."+d.charAt(0).toUpperCase()+d.substr(1)+"Plugin",function(){E.call(this,d,e);this._overwriteProps=h||[]},!0===a.global),
g=s.prototype=new E(d);g.constructor=s;s.API=a.API;for(c in k)"function"==typeof a[c]&&(g[k[c]]=a[c]);return s.version=a.version,E.activate([s]),s},t=n._gsQueue){for(p=0;t.length>p;p++)t[p]();for(c in B)B[c].func||n.console.log("GSAP encountered missing dependency: com.greensock."+c)}q=!1}})("undefined"!=typeof module&&module.exports&&"undefined"!=typeof global?global:this||window,"TweenLite");var _gsScope="undefined"!=typeof module&&module.exports&&"undefined"!=typeof global?global:this||window;
(_gsScope._gsQueue||(_gsScope._gsQueue=[])).push(function(){_gsScope._gsDefine("easing.Back",["easing.Ease"],function(n){var C,x,t,p=_gsScope.GreenSockGlobals||_gsScope,c=2*Math.PI,m=Math.PI/2,q=p.com.greensock._class,w=function(a,c){var h=q("easing."+a,function(){},!0),m=h.prototype=new n;return m.constructor=h,m.getRatio=c,h},r=n.register||function(){},y=function(a,c,h,n){c=q("easing."+a,{easeOut:new c,easeIn:new h,easeInOut:new n},!0);return r(c,a),c},v=function(a,c,h){this.t=a;this.v=c;h&&(this.next=
h,h.prev=this,this.c=h.v-c,this.gap=h.t-a)},z=function(a,c){var h=q("easing."+a,function(a){this._p1=a||0===a?a:1.70158;this._p2=1.525*this._p1},!0),m=h.prototype=new n;return m.constructor=h,m.getRatio=c,m.config=function(a){return new h(a)},h},z=y("Back",z("BackOut",function(a){return(a-=1)*a*((this._p1+1)*a+this._p1)+1}),z("BackIn",function(a){return a*a*((this._p1+1)*a-this._p1)}),z("BackInOut",function(a){return 1>(a*=2)?.5*a*a*((this._p2+1)*a-this._p2):.5*((a-=2)*a*((this._p2+1)*a+this._p2)+
2)})),B=q("easing.SlowMo",function(a,c,h){null==a?a=.7:1<a&&(a=1);this._p=1!==a?c||0===c?c:.7:0;this._p1=(1-a)/2;this._p2=a;this._p3=this._p1+this._p2;this._calcEnd=!0===h},!0),h=B.prototype=new n;return h.constructor=B,h.getRatio=function(a){var c=a+(.5-a)*this._p;return this._p1>a?this._calcEnd?1-(a=1-a/this._p1)*a:c-(a=1-a/this._p1)*a*a*a*c:a>this._p3?this._calcEnd?1-(a=(a-this._p3)/this._p1)*a:c+(a-c)*(a=(a-this._p3)/this._p1)*a*a*a:this._calcEnd?1:c},B.ease=new B(.7,.7),h.config=B.config=function(a,
c,h){return new B(a,c,h)},C=q("easing.SteppedEase",function(a){a=a||1;this._p1=1/a;this._p2=a+1},!0),h=C.prototype=new n,h.constructor=C,h.getRatio=function(a){return 0>a?a=0:1<=a&&(a=.999999999),(this._p2*a>>0)*this._p1},h.config=C.config=function(a){return new C(a)},x=q("easing.RoughEase",function(a){a=a||{};for(var c,h,m,q,p=a.taper||"none",t=[],w=0,r=q=0|(a.points||20),x=!1!==a.randomize,y=!0===a.clamp,z=a.template instanceof n?a.template:null,A="number"==typeof a.strength?.4*a.strength:.4;-1<
--r;)a=x?Math.random():1/q*r,c=z?z.getRatio(a):a,"none"===p?h=A:"out"===p?(m=1-a,h=m*m*A):"in"===p?h=a*a*A:.5>a?(m=2*a,h=.5*m*m*A):(m=2*(1-a),h=.5*m*m*A),x?c+=Math.random()*h-.5*h:r%2?c+=.5*h:c-=.5*h,y&&(1<c?c=1:0>c&&(c=0)),t[w++]={x:a,y:c};t.sort(function(a,c){return a.x-c.x});h=new v(1,1,null);for(r=q;-1<--r;)q=t[r],h=new v(q.x,q.y,h);this._prev=new v(0,0,0!==h.t?h:h.next)},!0),h=x.prototype=new n,h.constructor=x,h.getRatio=function(a){var c=this._prev;if(a>c.t){for(;c.next&&a>=c.t;)c=c.next;c=
c.prev}else for(;c.prev&&c.t>=a;)c=c.prev;return this._prev=c,c.v+(a-c.t)/c.gap*c.c},h.config=function(a){return new x(a)},x.ease=new x,y("Bounce",w("BounceOut",function(a){return 1/2.75>a?7.5625*a*a:2/2.75>a?7.5625*(a-=1.5/2.75)*a+.75:2.5/2.75>a?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375}),w("BounceIn",function(a){return 1/2.75>(a=1-a)?1-7.5625*a*a:2/2.75>a?1-(7.5625*(a-=1.5/2.75)*a+.75):2.5/2.75>a?1-(7.5625*(a-=2.25/2.75)*a+.9375):1-(7.5625*(a-=2.625/2.75)*a+.984375)}),w("BounceInOut",
function(a){var c=.5>a;return a=c?1-2*a:2*a-1,a=1/2.75>a?7.5625*a*a:2/2.75>a?7.5625*(a-=1.5/2.75)*a+.75:2.5/2.75>a?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375,c?.5*(1-a):.5*a+.5})),y("Circ",w("CircOut",function(a){return Math.sqrt(1-(a-=1)*a)}),w("CircIn",function(a){return-(Math.sqrt(1-a*a)-1)}),w("CircInOut",function(a){return 1>(a*=2)?-.5*(Math.sqrt(1-a*a)-1):.5*(Math.sqrt(1-(a-=2)*a)+1)})),t=function(a,h,m){var p=q("easing."+a,function(a,h){this._p1=a||1;this._p2=h||m;this._p3=
this._p2/c*(Math.asin(1/this._p1)||0)},!0);a=p.prototype=new n;return a.constructor=p,a.getRatio=h,a.config=function(a,c){return new p(a,c)},p},y("Elastic",t("ElasticOut",function(a){return this._p1*Math.pow(2,-10*a)*Math.sin((a-this._p3)*c/this._p2)+1},.3),t("ElasticIn",function(a){return-(this._p1*Math.pow(2,10*(a-=1))*Math.sin((a-this._p3)*c/this._p2))},.3),t("ElasticInOut",function(a){return 1>(a*=2)?-.5*this._p1*Math.pow(2,10*(a-=1))*Math.sin((a-this._p3)*c/this._p2):.5*this._p1*Math.pow(2,-10*
(a-=1))*Math.sin((a-this._p3)*c/this._p2)+1},.45)),y("Expo",w("ExpoOut",function(a){return 1-Math.pow(2,-10*a)}),w("ExpoIn",function(a){return Math.pow(2,10*(a-1))-.001}),w("ExpoInOut",function(a){return 1>(a*=2)?.5*Math.pow(2,10*(a-1)):.5*(2-Math.pow(2,-10*(a-1)))})),y("Sine",w("SineOut",function(a){return Math.sin(a*m)}),w("SineIn",function(a){return-Math.cos(a*m)+1}),w("SineInOut",function(a){return-.5*(Math.cos(Math.PI*a)-1)})),q("easing.EaseLookup",{find:function(a){return n.map[a]}},!0),r(p.SlowMo,
"SlowMo","ease,"),r(x,"RoughEase","ease,"),r(C,"SteppedEase","ease,"),z},!0)});_gsScope._gsDefine&&_gsScope._gsQueue.pop()();
(function(){for(var n=0,C=["ms","moz","webkit","o"],x=0;x<C.length&&!window.requestAnimationFrame;++x)window.requestAnimationFrame=window[C[x]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[C[x]+"CancelAnimationFrame"]||window[C[x]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(t,p){var c=(new Date).getTime(),m=Math.max(0,16-(c-n)),q=window.setTimeout(function(){t(c+m)},m);n=c+m;return q});window.cancelAnimationFrame||(window.cancelAnimationFrame=
function(n){clearTimeout(n)})})();
(function(){function n(){v=[];for(var h=0;h<q;h+=q/20)for(var a=0;a<w;a+=w/20){var f=h+Math.random()*q/20,n=a+Math.random()*w/20;v.push({x:f,originX:f,y:n,originY:n})}for(h=0;h<v.length;h++){a=[];f=v[h];for(n=0;n<v.length;n++){var p=v[n];if(f!=p){for(var t=!1,r=0;4>r;r++)t||void 0!=a[r]||(a[r]=p,t=!0);for(r=0;4>r;r++)!t&&m(f,p)<m(f,a[r])&&(a[r]=p,t=!0)}}f.closest=a}for(h in v)a=new c(v[h],2+2*Math.random(),"rgba(255,255,255,.2)"),v[h].circle=a}function C(c){var a=posy=0;if(c.pageX||c.pageY)a=c.pageX,
posy=c.pageY;else if(c.clientX||c.clientY)a=c.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,posy=c.clientY+document.body.scrollTop+document.documentElement.scrollTop;z.x=a;z.y=posy}function x(){t();for(var c in v)p(v[c])}function t(){if(B){y.clearRect(0,0,q,w);for(var c in v){4E3>Math.abs(m(z,v[c]))?(v[c].active=.3,v[c].circle.active=.6):2E4>Math.abs(m(z,v[c]))?(v[c].active=.1,v[c].circle.active=.3):4E4>Math.abs(m(z,v[c]))?(v[c].active=.02,v[c].circle.active=.1):(v[c].active=
0,v[c].circle.active=0);var a=v[c];if(a.active){var f=void 0;for(f in a.closest)y.beginPath(),y.moveTo(a.x,a.y),y.lineTo(a.closest[f].x,a.closest[f].y),y.strokeStyle="rgba(18, 134, 140,"+a.active+")",y.stroke()}v[c].circle.draw()}}requestAnimationFrame(t)}function p(c){TweenLite.to(c,1+1*Math.random(),{x:c.originX-50+100*Math.random(),y:c.originY-50+100*Math.random(),ease:Circ.easeInOut,onComplete:function(){p(c)}})}function c(c,a,f){var m=this;m.pos=c||null;m.radius=a||null;m.color=f||null;this.draw=
function(){m.active&&(y.beginPath(),y.arc(m.pos.x,m.pos.y,m.radius,0,2*Math.PI,!1),y.fillStyle="rgba(18, 134, 140,"+m.active+")",y.fill())}}function m(c,a){return Math.pow(c.x-a.x,2)+Math.pow(c.y-a.y,2)}var q,w,r,y,v,z,B=!0;q=window.innerWidth;w=window.innerHeight;z={x:q/2,y:w/2};r=document.getElementById("canvas-points");r.width=q;r.height=w;y=r.getContext("2d");n();x();"ontouchstart"in window||window.addEventListener("mousemove",C);window.addEventListener("scroll",function(){B=document.body.scrollTop>
w?!1:!0});window.addEventListener("resize",function(){q=window.innerWidth;w=window.innerHeight;768>q?(r.width=0,r.height=0):(r.width=q,r.height=w,n(),x())})})();