export {
  aboutBlock,
  aboutOrganizerBlock,
  addToHomeScreen,
  buyTicket,
  codeOfConduct,
  dates,
  emailUs,
  featuredVideos,
  feedback,
  filters,
  followOur,
  followUs,
  footer,
  footerRelBlock,
  galleryBlock,
  latestPostsBlock,
  loading,
  mapBlock,
  mySchedule,
  notifications,
  offlineMessage,
  partnersBlock,
  previousSpeakersBlock,
  schedule,
  signIn,
  signInDialog,
  signOut,
  speakersBlock,
  subscribeBlock,
  subscribeNote,
  timezoneOffset,
  title,
} from '../../data/resources.json';
export {
  contentLoaders,
  hashtag,
  heroSettings,
  location,
  mailto,
  navigation,
  organizer,
  signInProviders,
  socialNetwork,
} from '../../data/settings.json';
