export {
  aboutBlock,
  aboutOrganizerBlock,
  addToHomeScreen,
  buyTicket,
  codeOfConduct,
  dates,
  emailUs,
  feedback,
  followOur,
  followUs,
  footer,
  footerRelBlock,
  notifications,
  offlineMessage,
  signIn,
  signInDialog,
  signOut,
  subscribeBlock,
  subscribeNote,
  title,
} from '../../data/resources.json';
export {
  hashtag,
  heroSettings,
  location,
  mailto,
  navigation,
  organizer,
  signInProviders,
  socialNetwork,
} from '../../data/settings.json';
