name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: Create temp serviceAccount.json
        run: echo "{}" > serviceAccount.json
      - run: npm ci
      - run: npm run build
      - uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.FIREBASE_DEPLOY_SERVICE_ACCOUNT }}
      - run: npx firebase deploy --project hoverboard-master --non-interactive
